In [2]:
# open awanui as df
import pandas as pd

# Awanui stats

In [ ]:
AWANUI = r"C:\Users\tfo46\OneDrive - University of Canterbury\Tara_PhD\c_PhD\c_Data\a_source\sw_surface_water\HBRC_sw\river-flow-for-awanui-st.csv"
df = pd.read_csv(AWANUI)
df['m3pd'] = df['Awanui Stream at Flume (y)'] * 86.4 # convert Lps to m3/d

# calulate the mean and variance of the flow for each month
df['date'] = pd.to_datetime(df['Awanui Stream at Flume (x)'])
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
monthly_stats = df.groupby(['month','year'])['Awanui Stream at Flume (y)'].agg(['mean', 'std']).reset_index()

In [18]:
# if month is 10 or 11 then calculate mean and variance frm grouped data
df[df['month'].isin([10, 11])]['m3pd'].agg(['mean', 'std']).reset_index()

  index           m3pd
0  mean  100403.684736
1   std  115478.135223

In [19]:
# if month is 10 or 11 then calculate mean and variance frm grouped data
df[df['month'].isin([5])]['m3pd'].agg(['mean', 'std']).reset_index()

  index          m3pd
0  mean  46334.288988
1   std  56591.012536

# Poukawa Flow in

In [28]:
POUKAWA = r"C:\Users\tfo46\OneDrive - University of Canterbury\Tara_PhD\c_PhD\c_Data\a_source\sw_surface_water\HBRC_sw\river-flow-for-poukawa-s.csv"
df = pd.read_csv(POUKAWA)
df['m3pd'] = df['Poukawa Stream at Douglas Road (y)'] * 86.4 # convert Lps to m3/d

# calulate the mean and variance of the flow for each month
df['date'] = pd.to_datetime(df['Poukawa Stream at Douglas Road (x)'])
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
monthly_stats = df.groupby(['month','year'])['Poukawa Stream at Douglas Road (y)'].agg(['mean', 'std']).reset_index()

In [29]:
# if month is 10 or 11 then calculate mean and variance frm grouped data
df[df['month'].isin([10, 11])]['m3pd'].agg(['mean', 'std']).reset_index()

  index          m3pd
0  mean  26283.311416
1   std  31551.811867

In [ ]:
26283.311416/86.4

304.20499324074075

:

# Recharge variance

In [27]:
RF = r"C:\Users\tfo46\OneDrive - University of Canterbury\Tara_PhD\c_PhD\c_Data\a_source\clm_climate_data\datahub\3028__Rain__D.csv"
df = pd.read_csv(RF)

In [28]:
df.head()

,Frequency [D/H/S],Observation time UTC,Data Source,Rainfall [mm],PERIOD [hrs]
0,Daily,1917-03-01T21:00:00Z,D,0.0,24
1,Daily,1917-03-02T21:00:00Z,D,1.8,24
2,Daily,1917-03-03T21:00:00Z,D,1.0,24
3,Daily,1917-03-04T21:00:00Z,D,0.0,24
4,Daily,1917-03-05T21:00:00Z,D,1.0,24

In [31]:
# get daily average rainfall and variance for Oct and Nov
df['date'] = pd.to_datetime(df['Observation time UTC'])
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
monthly_stats = df.groupby(['month','year'])['Rainfall [mm]'].agg(['mean', 'var']).reset_index()
monthly_stats

     month  year      mean         var
0        1  1918  4.232258   78.093591
1        1  1919  0.767742   10.995591
2        1  1920  1.345161    8.365892
3        1  1921  0.187097    0.435161
4        1  1922  4.219355   49.952946
..     ...   ...       ...         ...
743     12  1980  7.319355  237.284946
744     12  1981  1.335484   27.492366
745     12  1982  0.180645    0.589613
746     12  1983  2.160870   21.989763
747     12  1984  1.877419   17.169140

[748 rows x 4 columns]

In [34]:
monthly_stats[monthly_stats['month'].isin([10, 11])].agg(['mean']).reset_index()['mean']

0    1.675488
Name: mean, dtype: float64

In [33]:
monthly_stats[monthly_stats['month'].isin([10, 11])].agg(['var']).reset_index()['mean']

0    1.348465
Name: mean, dtype: float64

In [36]:
(0.25/1.675488) * 1.348465

0.20120481316488092